### ISSUE TITLE
l1: text to number

### ISSUE THREAD

**Issue by Mironenko** [Mironenko/mgtu-cpp-public#1]
> Я тут пытаюсь писать первую лабу и застопорился на одном моменте. Могу я спросить совета?:)
> 
> Функция GetWindowText(hSide1, side1, 10); считывает то, что ввел пользователь в массив чариков (CHAR side1[] = {""}; - так у меня эта переменная задана в самом начале). Но мне надо каким-то образом это превратить в число, потом же арифметические действия с этим всем делать. На преобразование типа, а-ля dbside1 = (double)side1; VisualStudio ругается, а ничего лучше я пока не придумал.
> Не поможете разобраться, в чем проблема

**Comment by Mironenko** [comment]
CHAR // Юникод включен, стоит подумать о корректном типе

side1[] = {""}; // этот монстр пришел из c++; сколько в массиве символов?

https://msdn.microsoft.com/ru-ru/library/zkx076cy.aspx
https://msdn.microsoft.com/ru-ru/library/yd5xkb5c.aspx

**Comment by annafragor** [comment]
Вы говорили, должна быть возможность использовать разные системы счисления (2, 8, 16)
Это значит, что пользователь сначала выбирает систему, потом в этой системе вводит данные и ответ получает в этой системе или что пользователь вводит все в 10, а получает ответ в нужной системе?

**Comment by Mironenko** [comment]
@moskanka , new problem -> new issue https://github.com/Mironenko/mgtu-cpp-public/issues/3
