### ISSUE TITLE
LNK1168

### ISSUE THREAD

**Issue by AnastasiaVern** [Mironenko/mgtu-cpp-public#2]
Сначала программа компилирует все на ура, где-то на 4-5 раз компиляции возникает ошибка LNK 1168 ("не удается открыть файл.exe для записи"). Я прочла, что делать в таких ситуациях на msdn и даже установила программу Process Explorer,чтобы она выявила процесс, из-за которого дескриптор блокируется. Но она не выявила. И я не знаю ,что делать.. ибо в 5-й раз создавать новый проект -> новые формы мне уже сильно наскучило. Может, дело в коде? Что может вызвать такую ошибку? 
Заранее спасибо!

**Comment by Mironenko** [comment]
В диспетчере задач есть запущенный экземпляр вашей программы при возникновении ошибки?
Если да, то эта ошибка говорит о том, что вы некорректно обрабатываете закрытие программы.
Цикл обработки сообщений завершается после вызова PostQuitMessage. Нет вызова, а сделан только DestroyWindow -- программа остается работать в фоне.

**Comment by AnastasiaVern** [comment]
Да, при завершении процесса в диспетчере ошибка пропадает. Спасибо!
