### ISSUE TITLE
Вывод текста EditControl

### ISSUE THREAD

**Issue by prosayfer** [Mironenko/mgtu-cpp-public#4]
Проблема заключается в том, что текст из EditC. записывается в массив, потом переводится в числа, далее выполняются некоторые операции (работоспособность которых проверена), а далее следует обратная операция, которая записывает полученный результат в массив символов, далее все это отправляется уже в другой EC(вывод), но почему-то выводится то же, что было введено в первый EC, т.е. будто не было никаких операций. Не знаю, как бороться:(

![default](https://cloud.githubusercontent.com/assets/17249858/13101831/b4231dbc-d55a-11e5-90bf-78d4f2df3e92.png)

**Comment by Mironenko** [comment]
1. Нельзя ли посмотреть исходный код полностью?
2. Вы работаете с UNICODE-строками? Если да, то используются _wtoi  и _itow.
3. Попробуйте установить брейкпойнт на начало выполнения case и проверьте выполнение данного участка пошагово в режиме отладки.

**Comment by Mironenko** [comment]
https://habrahabr.ru/post/164193/
