### ISSUE TITLE
SendMessage(hList, LB_ADDSTRING, ...), когда диалог не отображен

### ISSUE THREAD

**Issue by annafragor** [Mironenko/mgtu-cpp-public#5]
А как сделать так, чтобы даже когда немодальное окно (открывающееся отдельно, нажатием кнопки на главном окне), на котором находится ListBох, ListBox все равно заполнялся?
SendMessage(hList, LB_ADDSTRING, NULL, (LPARAM)operation); - это работает, только если диалоговое окно, на котором находится этот список открыто.

**Comment by Mironenko** [comment]
Полагаю, вы в обработке закрытия окна с историей выполняете DestroyWindow. Если вы вместо этого диалог с историей создадите один раз (CreateDialog в InitInstance, например), а после этого только будете управлять его отображением посредством ShowWindow(hHistoryDlg, SW_SHOW) и ShowWindow(hHistoryDlg, SW_HIDE), никаких проблем с заполнением списка в те моменты, когда диалог не отображен, не будет.

**Comment by Noogler96** [comment]
Здравствуйте.
Когда нам надо сдать 2-ю лаб. работу и откуда взять задание?

**Comment by Mironenko** [comment]
Noogler96, это новый issue.
Выполнение второй лабораторной работы начнется 28го февраля, прием работы будет 7го марта. Задания пока нет. Если вы хотите потренироваться, посмотрите материалы https://github.com/Mironenko/mgtu-cpp-public/blob/master/labs/2/main.pdf, повторите материалы лекции, ознакомьтесь заданиями лабораторных 2 и 3 методички и почитайте книгу по программированию на C++. Если ориентироваться по книге "Язык программирования С++" Бьерна Страуструпа (издание 3), вам после первой лекции и прочтенного курса С должен быть известен материал глав 4, 5, 6, 7, 9, 10. Настоятельно рекомендую также ознакомиться с главами 2 и 3.
