### ISSUE TITLE
Winapi

### ISSUE THREAD

**Issue by stepanovi5** [Mironenko/mgtu-cpp-public#6]
Как вообще все происходит ??? С чего посоветуете начать если мне все непонятно , какие то классы какие то issusы что то еще , и если ли этому более доступное объяснение.   Мне это пока тяжело для понимания , когда я могу подойти чтобы вы смогли мне объяснить что да как ???

**Comment by Mironenko** [comment]
http://www.ozon.ru/context/detail/id/138365/
http://alenacpp.blogspot.ru/2006/09/blog-post_19.html
